// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/move.png
var resourceMovePngData []byte
var ResourceMovePng = &fyne.StaticResource{
	StaticName:    "move.png",
	StaticContent: resourceMovePngData,
}

//go:embed assets/drag.png
var resourceDragPngData []byte
var ResourceDragPng = &fyne.StaticResource{
	StaticName:    "drag.png",
	StaticContent: resourceDragPngData,
}

//go:embed assets/pan.png
var resourcePanPngData []byte
var ResourcePanPng = &fyne.StaticResource{
	StaticName:    "pan.png",
	StaticContent: resourcePanPngData,
}
